gurpriyabhatia/hire_a_nanny

db/migrate/20200201155047_add_column_to_users.rb, db/schema.rb
I added a name, addres and phone number columns to the User table
=> With User migration

app/models/nanny.rb, db/migrate/20200201161902_create_nannies.rb, db/migrate/20200201163714_change_column_default.rb, db/schema.rb, test/models/nanny_test.rb
Please check my nanny model :)
=> added nanny model and validations

Gemfile, Gemfile.lock, app/models/booking.rb, app/models/nanny.rb, app/models/user.rb, config/environment.rb, config/initializers/validates_timeliness.rb, config/locales/validates_timeliness.en.yml, db/migrate/20200202212207_create_bookings.rb, db/migrate/20200202213732_add_start_time_to_bookings.rb, db/schema.rb, test/models/booking_test.rb
Hi Team,
I have created the Bookings model and the migration. 
I also added a date and time format validation gem file but have not managed to figure out the correct usage in the model yet. It is meant to work like this https://www.rubydoc.info/gems/adzap-validates_timeliness/2.2.2#label-AMBIGUOUS+YEAR+THRESHOLD. 
No impact on model and migrations. But any suggestions on how to build the required validations are most welcome. 
Please review!
G
=> Created the Bookings Model and Migration

config/routes.rb
Hi Team - updated the routes - this is WIP and may need to be updated as we go.
=> Updated the Routes

Gemfile, Gemfile.lock, db/seeds.rb
Hey :)
I created a seed which will generate 5 random users and nannies.
Thanks!
=> created seed to generate 5 random nannies and users

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/create.html.erb, app/views/users/destroy.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, app/views/users/update.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/storage.yml, db/migrate/20200203123336_create_active_storage_tables.active_storage.rb, db/schema.rb, test/controllers/users_controller_test.rb
Hi 👋Girls,
I did "enhance" the User model in particular the ApplicationController (to add some fields like the user_name, address, phone_number) and save it into the DB, I added the cloudinary service to get a picture of the user once his signup...
1) gemfile with cloudinary (and so touch the env. file and push into gitignore)
2) config with the active storage service and cloudinary
3) run a migration with active storage
4) modify the devise sign up form...
=> with user model, active storage, cloudinary service and signup form

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/nannies_controller.rb, app/views/nannies/index.html.erb, test/controllers/nannies_controller_test.rb
Updated the Nannies controller and view with Index only. :)
=> Nannies controller

.gitignore, app/views/shared/_navbar.html.erb
I added an if statement to the end of the cloudinary tag, so the page should still load if the user has no image.
=> Fix banner image bug

app/controllers/nannies_controller.rb
Please review the updates to the show method.
=> Nannies Show Method

app/controllers/application_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/shared/_navbar.html.erb
Hi 👋 Girls,
I did update the edit form for user, I did check the persistance of fields into the DB and I slightly modified the navbar in order to personnalize the experience with a welcome message!
=> with the update my profile user model with the application controller

app/models/booking.rb, app/models/nanny.rb, app/models/review.rb, db/migrate/20200206203327_create_reviews.rb, db/schema.rb, test/models/review_test.rb
Hey, 
I created the review model 👍 
Thanks!
=> Create review model

Gemfile.lock, app/assets/stylesheets/application.scss, app/javascript/packs/application.js, app/models/booking.rb, app/views/bookings/_form.html.erb, app/views/bookings/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, db/migrate/20200206200433_add_date_time_format.rb, db/schema.rb, package.json, yarn.lock
Hi Girls 👋,
it takes time for me to start, from useless pundit setup then useless booking controller but evenutally I shipped something : 1) a migration for the format of the start_date/end_date/start_time and 2) a js set up to have a nice user experience for picking date...
Could be easily improved passing more options into the js function...and we have to dev methods in the bookings controller to digest the params[]...
=> with a migration for datetime and with flactpckr js

app/controllers/reviews_controller.rb, app/views/bookings/show.html.erb, app/views/reviews/new.html.erb, test/controllers/reviews_controller_test.rb
=> completed reviews controller and views

app/controllers/nannies_controller.rb, app/views/nannies/show.html.erb
I finished the nanny show page, which displays the reviews and has a link to the booking form. The booking form is a WIP - I need to speak to a TA about auto-filling the nanny.
=> Nanny view

db/migrate/20200211200948_add_bio_to_nanny.rb, db/schema.rb
I added the bio column to the nannies table :)
=> added bio column to nanny table

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_styles.scss, app/assets/stylesheets/config/_colors.scss, app/views/nannies/show.html.erb
=> Styling for Nanny Profile

db/seeds.rb
=> added missing single quote

app/assets/javascripts/application.js, app/controllers/nannies_controller.rb, app/views/nannies/index.html.erb, db/seeds.rb
=> fixed algolia search, so that images show

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_searchbar.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_nannies.scss, app/controllers/nannies_controller.rb, app/views/nannies/index.html.erb
=> Nanny index ordering and search bar

app/controllers/nannies_controller.rb
Sorry, just a small fix because the nannies were in the wrong order...
=> fixed order of nannies

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_styles.scss, app/views/bookings/show.html.erb, app/views/nannies/show.html.erb, app/views/shared/_navbar.html.erb, config/initializers/rails_defaults.rb
Added styling to the viewings.
=> A lot of styling stuff

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_styles.scss, app/controllers/bookings_controller.rb, app/views/bookings/_form.html.erb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb, app/views/nannies/index.html.erb, app/views/nannies/show.html.erb
=> Move new booking button

app/assets/stylesheets/components/_styles.scss, app/views/bookings/edit.html.erb
=> Fix booking form background
